### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by Acidsly** [aleho/onlyoffice-ce-docker-license#1]
Git version: 1.8.3.1
I got an error for command
docker build \
    --tag=onlyoffice-patched \
    https://github.com/aleho/onlyoffice-ce-docker-license.git

Step 1/15 : ARG oo_version=5.6.2.2
Please provide a source image with 'from' prior to commit

**Comment by aleho** [comment]
What's you docker version?

Just checked and it works here:
```
docker build \
    --tag=onlyoffice-patched \
    https://github.com/aleho/onlyoffice-ce-docker-license.git
```

```
Sending build context to Docker daemon  71.17kB
Step 1/15 : ARG oo_version=5.6.2.2
Step 2/15 : FROM onlyoffice/documentserver:$oo_version
5.6.2.2: Pulling from onlyoffice/documentserver
```

**Comment by Acidsly** [comment]
> What's you docker version?

Docker version 1.13.1 build 64e9980/1.13.1

**Comment by aleho** [comment]
This is very outdated and prone to fail. Consider updating to a newer docker release / distribution.
