### ISSUE TITLE
oo6.1.1 can't open doc

### ISSUE THREAD

**Issue by liamhaely-dev** [aleho/onlyoffice-ce-docker-license#14]
When opening a word document, it will be stuck in the loading interface

**Comment by aleho** [comment]
This can happen with a broken container.

Make sure you're pulling the version again to have a very recent build. A building error resulting in a FrankenOffice mixture of versions.

Also, check `https://youroffice.domain/web-apps/apps/api/documents/api.js`. If it says `6.1.0` you are running the broken container.

**Comment by liamhaely-dev** [comment]
thanks

**Comment by liamhaely-dev** [comment]
But excel PPT is normal

**Comment by mhaluska** [comment]
@24444871  I tested .xlsx, .docx and .pptx... everything works fine with image `alehoho/oo-ce-docker-license:6.1.1.53`.
