### ISSUE TITLE
What I pull down is version 6.2.2

### ISSUE THREAD

**Issue by liamhaely-dev** [aleho/onlyoffice-ce-docker-license#20]
What I pull down is version 6.2.2？

**Comment by nokoa77** [comment]
I confirm. 

Cause : in hub.docker, "latest" tag was not updated to 6.3

Solution for me : call "alehoho/oo-ce-docker-license:6.3.0.111" instead of "alehoho/oo-ce-docker-license" in my docker command. 

For eg. : 
> docker run     -v /app/onlyoffice/DocumentServer/logs:/var/log/onlyoffice      -v /app/onlyoffice/DocumentServer/data:/var/www/onlyoffice/Data      -v /app/onlyoffice/DocumentServer/lib:/var/lib/onlyoffice     -v /app/onlyoffice/DocumentServer/db:/var/lib/postgresql     --name=onlyoffice     --detach     --publish=8443:443     alehoho/oo-ce-docker-license:6.3.0.111

Thank you, @aleho, for this very usefull repo,

Bruno

**Comment by kikislater** [comment]
6.3.1.32 is out now
https://github.com/ONLYOFFICE/DocumentServer/releases

**Comment by liamhaely-dev** [comment]
thx,nokoa77
