### ISSUE TITLE
Problems building 6.3.1.32

### ISSUE THREAD

**Issue by klou** [aleho/onlyoffice-ce-docker-license#26]
I can pull the image and use that, but for some reason, building the image results in the following error:
```
$ docker build     --tag=onlyoffice-patched   https://github.com/aleho/onlyoffice-ce-docker-license.git
unable to prepare context: unable to 'git clone' to temporary context directory: error fetching: fatal: couldn't find remote ref master
: exit status 128
```
I've run the ```git clone``` commands separately without any problem, using ```--branch v6.3.1.32```, so this is just a problem building.

**Comment by aleho** [comment]
Yes, I see what's the problem here. Docker seems to always assume a master branch, but as of lately a lot of repositories have been moving away from master to main (and I personally think that's a good thing).

Could update the docs, but not much else I'm afraid.
