### ISSUE TITLE
How to integrate your docker onlyoffice with alfresco

### ISSUE THREAD

**Issue by skynet-dev** [aleho/onlyoffice-ce-docker-license#27]
Hello !

Iam trying to integrate your docker onlyoffice unlimited with alfresco but how ?
i informe you in windows when i test is onlyoffice is running taping : this url : http://127.0.0.1:8083  or ip adrress  of host  example my ip adrress is : 192.168.0.200 so http://192.168.0.200:8083  its still working and so putting the url : in alfresco share : 

   Configuration d'ONLYOFFICE Document Server in alfresco :

![AlfresOnlyoffice Integration](https://user-images.githubusercontent.com/26434401/126834296-f311819d-7b1a-40d7-a150-abd4972624a6.jpg)

**Comment by aleho** [comment]
This is not a support forum.
Also, please don't ask the upstream developers about help with this image.

(see https://github.com/aleho/onlyoffice-ce-docker-license#notes)
