### ISSUE TITLE
Erorr connection between docker containers (onlyoffice&owncloud)

### ISSUE THREAD

**Issue by Acidsly** [aleho/onlyoffice-ce-docker-license#3]
Hi. I have a problem with connection between running onlyoffice docker and owncloud docker. When I try set in owncloud server params for connection to onlyoffice ( http://<IP_for_onlyoffice>) get error: Error when trying to connect (cURL error 7: Failed to connect to <IP_for_onlyoffice> port 80: No route to host) 
Checking work of onlyoffice by link: <IP_for_onlyoffice>/healthcheck is Ok. 
All dockers container running on one VM mashine with CentOS 7. 
I do verify work on host mashine
What I did incorrect?
P.S. Owncloud install by link: https://doc.owncloud.com/server/10.5/admin_manual/installation/docker/#logging-in

**Comment by aleho** [comment]
This image can be used like any other image, there's nothing special about it.
If it doesn't work for you, look for resources on how to use Docker and/or setup your cloud instance with OnlyOffice.

Sorry, but I can't provide Docker support here.
