### ISSUE TITLE
no mobile edit with 5.6.5.3

### ISSUE THREAD

**Issue by chvb** [aleho/onlyoffice-ce-docker-license#4]
Hello,

with the new 5.6.5.3 version the mobile editing doesn't work anymore.
With the previous version everything works perfekt.

Can you fix this? Many thanks!

**Comment by aleho** [comment]
What do you mean by "doesn't work anymore"?

**Comment by chvb** [comment]
Also wenn ich eine z.B. eine Excel Liste innerhalb der Nextcloud App öffne, bekomme ich die Meldung, dass dies nicht mit der Community Lösung funktioniert.
Mit dem Offiziellen Docker in der Version 5.5.0.165 und dem Patch von
https://github.com/Zegorax/OnlyOffice-Unlimited
funktioniert das ganze perfekt.
Ich habe deinen Beitrag im Nextcloud Forum ebenfalls verfolgt und da hattest du geschrieben, dass das "Mobile Edit" mit deiner Version ebenfalls funktioniert.
Es wäre wunderbar, wenn du das ganze nochmals prüfen könntest und im Idealfall das ganze auch funktionieren würde.
Dann hätten wir eine sauber funktionierende Lösung.

Ich möchte mich schon vielmals für deine Bemühungen bedanken.
Wenn ich irgendwie behilflich mit testen sein kann, mache ich das sehr gerne!

**Comment by jorsn** [comment]
Mit der Version 5.6.4.20 und diesem Container (aleho/onlyoffice-ce-docker-license) läuft es bei mir noch einwandfrei.

**Comment by chvb** [comment]
Diese Version hatte ich auch im Einsatz. Das stimmt auch soweit. Mobile Edit möglich allerdings nur auf einem Gerät. Auf einem zweiten hatte es dann nicht mehr funktioniert. Da kam wieder die Meldung, dass es mit der eingesetzten Lizenz nicht möglich ist.

**Comment by chvb** [comment]
<img width="430" alt="80311128-6b6dd300-87a3-11ea-9dcc-9d510684e067" src="https://user-images.githubusercontent.com/13118224/95255270-649ebe00-0821-11eb-8763-ff1cfc69f4fc.png">

**Comment by aleho** [comment]
Sorry, I cannot reproduce your problems here, though I can only test on one mobile and in a simulated Browser env at the same time. For me mobile editing via the Nextcloud app seems to work (at least in the latest version `6.0.0.105`).

Please also keep discussions in English, even if it's not your primary language. Not everyone is capable of understanding German.
