### ISSUE TITLE
Enhancement : use it in documentserver app

### ISSUE THREAD

**Issue by kikislater** [aleho/onlyoffice-ce-docker-license#7]
Any luck to have it working using Makefile of official app : 

https://github.com/nextcloud/documentserver_community/

https://github.com/nextcloud/documentserver_community/blob/master/Makefile

I replaced docker image by yours but fail on sed in version of Makefile

**Comment by kikislater** [comment]
Wait : same error with standard version from official app but works afterwards ...  whereas when I put your docker image it doesn't seem to work

**Comment by aleho** [comment]
This repository is meant to rebuild / patch a specific docker image, consisting of documentserver, database, message queue etc. (it's a single-image solution to get an instance of OO running in a container without having to worry about its setup).

If you want it to work in a different environment you'll have to find out how and which files to patch / enhance. I think that would be beyond the scope of this repository.

Anyways, I think the patches here will work with any setup of documentserver, and the Dockerfile should give you hints on how to build it.

**Comment by gituser** [comment]
You can use this license patch without docker on the debian system if you've installed onlyoffice via repository, all you need to do is to follow the instructions from the Dockerfile and replace `documentserver` and `converter` in the installed package.
